import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    main: {
      flexDirection: 'row',
      marginHorizontal: '1%',
      marginTop: 10,
      justifyContent: 'center',
    },
    list: {
      backgroundColor: 'white',
      width: '85%',
      borderStyle: 'solid',
      borderWidth: 2,
      borderColor: '#3949ab',
      borderTopLeftRadius: 5,
      borderTopRightRadius: 5,
      borderBottomLeftRadius: 5,
      borderBottomRightRadius: 5,
      flexDirection: 'row',
      alignItems: 'center',
    },
    buttonDel: {
      justifyContent: 'center',
      alignItems: 'center',
      width: '12%',
      marginLeft: '1%',
      backgroundColor: 'red',
      borderTopLeftRadius: 5,
      borderTopRightRadius: 5,
      borderBottomLeftRadius: 5,
      borderBottomRightRadius: 5,
    },
    buttonEdit: {
      justifyContent: 'center',
      alignItems: 'center',
      width: '12%',
      marginLeft: '1%',
      backgroundColor: 'orange',
      borderTopLeftRadius: 5,
      borderTopRightRadius: 5,
      borderBottomLeftRadius: 5,
      borderBottomRightRadius: 5,
    },
    del: {
      fontSize: 30,
      color: 'white',
    },
    inputeBlock: {
      flexDirection: 'row',
      margin: 2,
      justifyContent: 'center',
    },
    input: {
      backgroundColor: 'white',
      fontSize: 19,
      width: '75%',
      borderStyle: 'solid',
      borderWidth: 2,
      borderColor: '#3949ab',
      borderTopLeftRadius: 10,
      borderTopRightRadius: 10,
      borderBottomLeftRadius: 10,
      borderBottomRightRadius: 10,
    },
    add: {
      justifyContent: 'center',
      alignItems: 'center',
      marginHorizontal: '1%',
      width: '13%',
      backgroundColor: '#3949ab',
      borderTopLeftRadius: 10,
      borderTopRightRadius: 10,
      borderBottomLeftRadius: 10,
      borderBottomRightRadius: 10,
    },
    textBlock: {
      width: '90%',
      fontSize: 20,
    },
    text: {
      fontSize: 16,
    },
  });

  export { styles };